import Head from 'next/head'

export const metadata = {
  title: 'Log in - Zendegi',
  // description: 'Generated by create next app',
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>
}
