export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return <div className='min-h-screen bg-white'>{children}</div>
}
