import Head from 'next/head'

export const metadata = {
  title: 'Events - Zendegi',
  description: 'Generated by create next app',
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return <div className="min-h-screen bg-white">{children}</div>
}
