import Head from 'next/head'

// https://nextjs.org/docs/app/building-your-application/optimizing/metadata#seo

export const metadata = {
  title: 'Wedding - Zendegi',
  description: 'Generated by create next app',
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>
}
