import { Inter, Great_Vibes } from 'next/font/google'
import classNames from 'classnames'
import { headers, cookies } from 'next/headers'
import { dir } from 'i18next'

import { Analytics } from '@vercel/analytics/react'
import { fallbackLng } from '@/services/i18n'
import { getServerSideLanguage } from '@/services/i18n/serverSide'

import './globals.css'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

const greatVibes = Great_Vibes({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-great-vibes',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const cookieName = 'i18next'

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const lng = getServerSideLanguage()

  return (
    <html lang={lng} dir={dir(lng)} className="bg-white">
      <body
        className={classNames(
          inter.variable,
          greatVibes.variable,
          'min-h-max font-sans bg-white',
        )}
      >
        {children}
        <Analytics />
      </body>
    </html>
  )
}
