import './globals.css'
import { Inter, Great_Vibes } from 'next/font/google'
import classNames from 'classnames'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

const greatVibes = Great_Vibes({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-great-vibes',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={classNames(
          inter.variable,
          greatVibes.variable,
          'min-h-max font-sans bg-white',
        )}
      >
        {children}
      </body>
    </html>
  )
}
