import { Inter, Great_Vibes } from 'next/font/google'
import { notFound } from 'next/navigation'

import { useLocale, NextIntlClientProvider, createTranslator } from 'next-intl'

import classNames from 'classnames'

import './globals.css'

interface Params {
  locale: string
}

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

const greatVibes = Great_Vibes({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-great-vibes',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children, params }) {
  const locale = useLocale()

  // Validate that the incoming `locale` parameter is a valid locale
  if (params.locale !== locale) {
    notFound()
  }

  let messages
  try {
    messages = (await import(`../../messages/${locale}.json`)).default
  } catch (error) {
    notFound()
  }

  return (
    <html lang="en" className="bg-white">
      <body
        className={classNames(
          inter.variable,
          greatVibes.variable,
          'min-h-max font-sans bg-white',
        )}
        dir="ltr"
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
